CREATE TABLE blog (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      title VARCHAR(255) NOT NULL,
                      text TEXT,
                      post_date TIMESTAMP
);